# Generated by Django 5.1.3 on 2024-12-05 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginproject_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logindetails',
            name='mobilenumber',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='logindetails',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
